POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": "detalhes do evento",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/9f1938c0-a954-44af-b7a3-51e7e4b94f0c/attendees
Content-Type: application/json

{
  "name": "William G",
  "email": "willis@gmail.com"
}

###

GET http://localhost:3333/events/9f1938c0-a954-44af-b7a3-51e7e4b94f0c

###

GET http://localhost:3333/attendees/3/badge